### ISSUE TITLE
The play button is no longer synced with the player

### ISSUE THREAD

**Issue by metoule** [metoule/deezer-control#16]
The extension no longer properly detects that Deezer is playing: the button is stuck on the play state, and doesn't update. It's no longer possible to pause / resume from the popup.

**Comment by ybonnamy** [comment]
Hi, got such a bug too, i'd be glad to see technical details explained here to better understand the mysteries around the issue.

**Comment by metoule** [comment]
Hi @ybonnamy, there's not much mystery :) 
The Deezer site has probably been updated, and I have to update the extension to match the new code. I'll try to fix this later today, thanks for your patience!

**Comment by metoule** [comment]
Fixed in version 2.17. It will be automatically deployed once the new version is reviewed by Google.
